[[Transport]] # 此处必须为双中括号，表示数组
Ip = "127.0.0.1" # 内网机公网IP
TargetHost = "127.0.0.1" # 与inner.toml一致
TargetPort = 8888 # 与inner.toml一致
Symkey = "0123456789012345" # 与innter.toml Auth.Symkey一致
LocalPort = 13000 # 手动指定在服务器上映射的端口

[[Transport]]
Ip = "127.0.0.1"
TargetHost = "x.x.x.x"
TargetPort = 4403
Symkey = "0123456789012345"
LocalPort = 13001 
KeepAlive = true

[CmdServer]
Port = 3333 # 命令端口监听地址，内网机会访问这个端口，记得开放云服务器防火墙

[ProxyServer] # 每个transport都会在outer服务上随机映射一个端口（如果transport配置段LocalPort = 0的话）
MinPort = 13000 # 随机分配的最小端口
MaxPort = 14000 # 随机分配的最大端口

[HttpServer]
Port = 8888  # http管理端口

[Global]
WaitNewConnSeconds = 5