[Auth]
Name = "test1"
Symkey = "0123456789012345"


[[Transport]]                   # 可以映射多个服务
TargetPort = 8877               # 要映射到外网服务的端口
TargetHost = "127.0.0.1"        # 要映射到外网服务的地址
ServerIp = "40.122.34.113"          # 云服务器地址
ServerPort = 8085              # 云服务命令端口
