[Auth]
Name = "test1"
Symkey = "0123456789012345"

[[Transport]]
TargetPort = 8888 # 要映射出去的端口
TargetHost = "127.0.0.1" # 
ServerIp = "127.0.0.1"
ServerPort = 3333

[[Transport]]
TargetPort = 4403
TargetHost = "118.25.195.227"
ServerIp = "127.0.0.1"
ServerPort = 3333
